version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    working_dir: /src
    volumes:
      - ./src:/src
  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - /db/mysql_data:/var/lib/mysql
